Algoritmo "Questao 3"

Var
   lucroJan,lucroFev,lucroMar,mediaLucro: real
   totalMeses: inteiro
Inicio
   escreval("Informe o lucro do mês de janeiro ")
   leia(lucroJan)
   escreval("Informe o lucro do mês de fevereiro ")
   leia(lucroFev)
   escreval("Informe o lucro do mês de março")
   leia(lucroMar)
   escreval ("Informe o total de meses")
   leia(totalMeses)
   mediaLucro<- lucroJan+lucroFev+lucroMar /totalMeses
   escreval (mediaLucro)
Fimalgoritmo